### ISSUE TITLE
First line of the abstract is too long on the PDF (typesetting issue?)

### ISSUE THREAD

**Issue by philipcardiff** [OpenFOAM-Journal/paperLatexTemplate#1]
The first line of the abstract is too long on the PDF (typesetting issue?); you do not notice it in the current example because the abstract is less than one line in length.

**Comment by MakisH** [comment]
I cannot reproduce this. Could you give a minimal working examle?

**Comment by philipcardiff** [comment]
I can also not reproduce it. I guess it must have been resolved with the introduction of other changes. This issue can be closed.
