### ISSUE TITLE
Mixed content and style files

### ISSUE THREAD

**Issue by MakisH** [OpenFOAM-Journal/paperLatexTemplate#11]
This repository currently has all files in the same directory, including, for example:

- Content:
   - `ofj-template.tex` -> Could stay
   - `example.png` -> Could go to `./figures/`
   - `Bibliography.bin` -> Could stay
- Style:
   - `OpenFOAMJournal.pdf` and `OpenFOAMJournal.png` -> Could go to `./ofj/images`
   - `ofj.cls`, `ofjart.cls`, `jams-l.cls` -> Not sure if all of these are needed in their entirety, but they could be moved to `./ofj/`.
   - `orcidlink.sty`, `tensorNotation.sty`, `finiteVolumeNotation.sty` -> Could go into `./ofj/`
- Build artifacts and temporary files (e.g., as of #4):
   - `ofj-template.pdf` 
   - `ofj-template.[aux, bbl, blg, fdb_latexmk, fls, log, out] -> They could all go into `./build/` (or `./_build/`)

This feels a bit verbose, as one cannot easily find the files that are actually relevant for editing. It also makes transitioning from another journal/LaTeX template a bit complicated. Therefore, it would be good to at least separate the style files from the rest, so that one could only copy the directory.

If you agree with this (or some other) structure, I can move things around.

**Comment by ofjournal** [comment]
Hi Gerasimos,
I agree with your proposal. Can you please help us, by improving the template files organization?
Best,
Miguel

**Comment by MakisH** [comment]
I will propose some first changes before your next meeting.
