### ISSUE TITLE
Indentation of first paragraph of each section

### ISSUE THREAD

**Issue by MakisH** [OpenFOAM-Journal/paperLatexTemplate#15]
The current LaTeX template indents every paragraph. However, there is a [popular typographic practice](https://graphicdesign.stackexchange.com/a/93232/116387) (very nice book, btw) to not indent the first paragraph in a section, as it already comes after a section title. Personally, I find this additional indentation very distracting.

One can currently override this manually by setting a `\noindent` at the beginning of the respective paragraphs, but [we could even adapt the template itself](https://tex.stackexchange.com/questions/137395/no-indent-in-the-first-paragraph-in-amsart). Some templates do this by default (e.g., the default `article` class) and this seems to be a peculiarity of `amsart`.

**Comment by ofjournal** [comment]
@MakisH - As I mentioned in the PR this suggestion was not implemented. Thank you anyway for taking care of this.
