### ISSUE TITLE
Footnotes indentation

### ISSUE THREAD

**Issue by MakisH** [OpenFOAM-Journal/paperLatexTemplate#22]
Currently, footnotes seem to indent the first line, which looks strange if we have more than one line. Example:

```text
_______________
  1 This is a long footnote that takes
more than one line and looks strange.
  2 This is another footnote.
```

**Comment by ofjournal** [comment]
Hi Gerasimos,
Thank you again for your support. I'm sure this was not done intentionally. Is there a way to correct it in the template?
Best,
Miguel

**Comment by MakisH** [comment]
I will try to fix this before your next meeting.
