### ISSUE TITLE
Capitalization of author names and section headings

### ISSUE THREAD

**Issue by MakisH** [OpenFOAM-Journal/paperLatexTemplate#29]
_Originally posted by @ofjournal in https://github.com/OpenFOAM-Journal/paperLatexTemplate/issues/20#issuecomment-1411534256_

> Hi @MakisH, following your suggestion, would it be possible to extend the remove of uppercase enforcement to the author names, and section headings?
> Best,
> Miguel

**Comment by jmnobrega** [comment]
Hi @MakisH,

I was planning to advance with all pending PR tomorrow, because my agenda is a bit full today. But I'll give you the feedback about PR #30 now.

Best,

Miguel
