### ISSUE TITLE
When listing many OpenFOAM versions the text does not wrap and looks ugly

### ISSUE THREAD

**Issue by philipcardiff** [OpenFOAM-Journal/paperLatexTemplate#3]
When listing many OpenFOAM versions the text does not wrap and looks ugly

**Comment by MakisH** [comment]
This is because the metadata section is given as a `tabular` table. Converting to a `description` seems to help:

```tex
  % Software and Manuscript
  \begin{description}
    \footnotesize
    \item[DOI] \href{https://doi.org/\theDOI}{\@DOI}\\
    \item[Version(s)] \@OpenFOAMversions\\
    \item[Repo] \href{\theRepository}{\@Repository}
  \end{description}
```

(not perfect, needs alignment with the abstract, but something in this direction)

I can suggest a PR based on this.

**Comment by philipcardiff** [comment]
This seems like a good idea to me

**Comment by MakisH** [comment]
> This seems like a good idea to me

To me as well, but the `description` environment defined by the template does not accept any optional arguments. Without this, it is very complicated to fix the alignment of the labels, as described in #27:

![Screenshot from 2023-02-02 16-58-19](https://user-images.githubusercontent.com/4943683/216375870-2b283460-c1c9-4805-9b02-c18e9a65fffe.png)

I already invested quite some time trying to work around it, so I am open to suggestions.
