### ISSUE TITLE
Template for 2023

### ISSUE THREAD

**Issue by ofjournal** [OpenFOAM-Journal/paperLatexTemplate#34]
Hi @MakisH, @philipcardiff and @eulerian-solutions,

If we are all comfortable with the current template version, we should use it for all the papers published in 2023.

During this year we should not perform major changes to the template (e.g. force capital letters on Title or Page headings), to assure all the papers will have a similar look.

Obviously, bugs should be corrected and minor changes, which do not affect the manuscript format, can be performed.

@MakisH your efforts (and patience) to improve the paper template are really appreciated.

Best,

Miguel

**Comment by eulerian-solutions** [comment]
We should open a second branch for minor changes or ideas for future implementation, which we can merge then next year.

**Comment by philipcardiff** [comment]
I agree with you both. I suggest we create a "template2024" branch for future changes.

Of course, any critical bugs can still be merged into the current "master".

**Comment by MakisH** [comment]
I discovered two more bugfixes we should integrate:
- https://github.com/OpenFOAM-Journal/paperLatexTemplate/pull/35
- https://github.com/OpenFOAM-Journal/paperLatexTemplate/pull/36

Other than that, I agree with the feature freeze and the separate branch for 2024. I don't see anything major. I have some ideas, but they can wait.

Please wait in case we discover anything else by, e.g., tomorrow, and then we could make a tagged release.

**Comment by ofjournal** [comment]
I Merged both. Thank you @MakisH for all your valuable help.

**Comment by eulerian-solutions** [comment]
Thank you for the fast processing of things to the both of you!

**Comment by MakisH** [comment]
If you are ready, you can now make a release: https://github.com/OpenFOAM-Journal/paperLatexTemplate/releases

This will introduce a Git tag with the version you provide (I suggest the naming scheme `year.patch`, i.e., `v2023.0`) and create an archive.

**Comment by ofjournal** [comment]
Hi @MakisH,

Thank you for the recommendation, I just prepared the release.

Are you able to see the draft?

In the affirmative case, can you please confirm everything is correct?

Best,

Miguel

**Comment by MakisH** [comment]
@ofjournal I cannot see the draft, since I am only an external collaborator to this repository/organization.

**Comment by jmnobrega** [comment]
@MakisH I just added you to the repository. I believe now you can see the draft.
Can you please confirm everything is correct?

**Comment by MakisH** [comment]
@jmnobrega yes, this looks correct to me.

By the way, there is no reason to comment or act as @ofjournal. This is rather uncommon. Such an account would be useful for bot-like activities (e.g., automatic pushes to some repository, etc).

**Comment by jmnobrega** [comment]
@MakisH You are right. I'll proceed accordingly from now on.
