### ISSUE TITLE
Article type in the build artifact name

### ISSUE THREAD

**Issue by MakisH** [OpenFOAM-Journal/paperLatexTemplate#9]
A [guideline](https://journal.openfoam.com/index.php/ofj/authorGuidelines) of the journal is:

> Rename the template to a file name which Identifies the selected journal Section ("FullPaper" for Full Papers, "TNote" for Technical Notes,  or "RevPaper" for Review Papers).

I would modify the Makefile (see #4) to include the `_FullPaper` or `_TNote` at the build artifact's name.

I can do that eventually.

**Comment by ofjournal** [comment]
Hi Gerasimos,
I agree it would be very useful. Can you please implement it?
Best,
Miguel

**Comment by MakisH** [comment]
I will implement this before your next meeting.
